data:
  path_object: './data/raw/MOS'
  train_split: 300

train:
  batch_size: 6

eval:
  batch_size: 1

hyperparameters:
  lr: 0.0001
  step_size: 2
  gamma: 0.2
  epochs: 150
  num_layer: 2
  node_feature_size: 128
  edge_feature_size: 128
  gcn_hidden_feature_size: 256
  dim_obj: 3
  dim_edge: 28
  num_obj_cls: 4
  num_rel_cls: 5
  num_node: 4
